// <auto-generated />
using Get_Projekat.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Get_Projekat.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201225161137_InitialMigration2")]
    partial class InitialMigration2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Get_Projekat.Model.Ispit", b =>
                {
                    b.Property<string>("BrojIndeksa")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("PredmetId")
                        .HasColumnType("bigint");

                    b.Property<short>("Ocena")
                        .HasColumnType("smallint");

                    b.Property<string>("StudentBrojIndeksa")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BrojIndeksa", "PredmetId");

                    b.HasIndex("StudentBrojIndeksa");

                    b.ToTable("Ispiti");
                });

            modelBuilder.Entity("Get_Projekat.Model.Student", b =>
                {
                    b.Property<string>("BrojIndeksa")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrojIndeksa");

                    b.ToTable("Studenti");
                });

            modelBuilder.Entity("Get_Projekat.Model.Ispit", b =>
                {
                    b.HasOne("Get_Projekat.Model.Student", null)
                        .WithMany("ListaIspita")
                        .HasForeignKey("StudentBrojIndeksa");
                });

            modelBuilder.Entity("Get_Projekat.Model.Student", b =>
                {
                    b.Navigation("ListaIspita");
                });
#pragma warning restore 612, 618
        }
    }
}
